/*
* generated by Xtext
*/
package org.xtext.example.xpt.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.xpt.services.XptGrammarAccess;

public class XptParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XptGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.xpt.parser.antlr.internal.InternalXptParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.xpt.parser.antlr.internal.InternalXptParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public XptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
