/*
 * generated by Xtext
 */
package org.xtext.example.xpt;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XptRuntimeModule extends org.xtext.example.xpt.AbstractXptRuntimeModule {

}
